addon-name: "Lib's - Item Highlighter"
addon-description: "highlights items in bags and inventory"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/libs-itemhighlighter"
  wago: "https://addons.wago.io/addons/b6mb29KP"
  discord: "https://discord.gg/Qc9TRBv"
