addon-name: "Libs - Item Highlighter"
addon-description: "highlights items in bags and inventory"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/libs-itemhighlighter"
  wago: "https://addons.wago.io/addons/b6mb29KP"
  discord: "https://discord.gg/Qc9TRBv"

# Secondary addon identity (BetterBags-Openable) is packaged via
# .pkgmeta-betterbags with -p 1021681 -a aNevMb62 in CI-CD.yml
